[package]
name = "steven_protocol"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>", "iceiix <ice_ix@protonmail.ch>" ]
edition = "2018"

[dependencies]
serde = "1.0.91"
serde_json = "1.0.39"
hex = "0.3.2"
sha-1 = "0.8.1"
aes = "0.3.2"
cfb8 = "0.3.2"
byteorder = "1.2.7"
log = { version = "0.4.6", features = ["std"] }
flate2 = { version = "1.0.7", features = ["rust_backend"], default-features = false }
num-traits = "0.2.8"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = "0.9.17"
